# Colors (Solarized Light)
[colors.primary]
  background = "#262a33"
  foreground = "#e5e5e5"

# Cursor colors
[colors.cursor]
  cursor = "#f8f8f0"
  text = "#cfcfc2"

[colors.selection]
  background = "#5a5c62"
  text = "#ece7e7"

# Normal colors
[colors.normal]
  black = "#000000"
  blue = "#2472c8"
  cyan = "#0fa8cd"
  green = "#05bc79"
  magenta = "#bc3fbc"
  red = "#cd3131"
  white = "#e5e5e5"
  yellow = "#e5e512"

# Bright colors
[colors.bright]
  black = "#666666"
  blue = "#2472c8"
  cyan = "#0fa8cd"
  green = "#05bc79"
  magenta = "#bc3fbc"
  red = "#cd3131"
  white = "#e5e5e5"
  yellow = "#e5e512"
